### ISSUE TITLE
Error trying to read config.json after clean install

### ISSUE THREAD

**Issue by gvuyk** [de-luca/electron-json-config#16]
**Expected behavior:**
After a clean install, the config file is created/loaded after the `userData` directory is created by electron

**Actual behavior:**
After a clean install, the module tries to create the config.json file before electron gets a chance to create the `userData` directory, throwing an error, crashing the app.
Subsequent app starts work fine since then the `userData` directory already exist (electron manages to create it after the first exception, maybe a race condition)

**Workaround**
Require electron-json-config on electron's `ready` callback

electron-json-config 1.5.0
electron 1.6.7
Windows 10

**Comment by de-luca** [comment]
Thank you for the report, I'll look into it

**Comment by framerate** [comment]
Was this never released? I'm still getting this error, I believe

`"electron-json-config": "^1.5.0",`

![image](https://user-images.githubusercontent.com/74291/35487641-cbea5f24-0432-11e8-8ed8-8e710c4617d3.png)

**Comment by de-luca** [comment]
Thank you, it seems I messed up back then and never actually published on NPM.
This is now published under tag `1.5.1`.
Sorry for the inconvenience caused.

**Comment by framerate** [comment]
Thank you! No big deal, just glad it got fixed! 

<3

**Comment by framerate** [comment]
@de-luca Did something else change 1.50 -> 1.5.1 ?

My settings from JSON don't seem to be being respected since I upgraded... :(

**Comment by de-luca** [comment]
Mostly documentation test and ci has changed since 1.5.0.  
You can see the diff here: https://github.com/de-luca/electron-json-config/compare/1.5.0...1.5.1

**Comment by framerate** [comment]
Well something else appears to have changed. I had to roll back to 1.5.0 and push an emergency hotfix because my JSON settings were not being respected. I haven't looked into it, so I guess it could be on my end but it's super weird.

I store 2 import things with this package. `fullscreen: true | false` and `muted: true | false`. 

With 1.5.1 and `fullscreen: false` the app loads in fullscreen. The option though THINKS I'm still in windowed mode and says "Go Fullscreen". Clicking it KEEPS ME FULL SCREEN but the option changes to "Go Windowed"

So what I would think is that maybe it was storing data as a bool before but now it's a string, or some conversion that changed?

Like I said... or it's probably something on my end I'm doing silly buy 1.5.0 works perfectly (except the crash on install). 1.5.1 is a dud if I just drop it in so something is wonky somewhere. If I find more I'll let you know, otherwise I'll have to PR and roll my own solution :/

**Comment by de-luca** [comment]
Looks like a type mismatch indeed, I'll check the tests and try to reproduce.
